services:
  web:
    build: .
    ports:
      - "8080:3000"
  pocketbase:
    build: ./pocketbase
#    image: adamcanard/pocketbase:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pocketbase-data:/pb_data
volumes:
  pocketbase-data:
