name: Publish to remote docker through SSH on push to release branch
on:
  push:
    branches:
      -  'release'
jobs:
  publish-in-docker:
    uses: JeremyCCox/jman-docker-workflow/.github/workflows/main.yml@main
    secrets:
      DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}
      PORT: ${{ secrets.PORT }}
